### PR TITLE
One more piece of ultra-hype

### PR DESCRIPTION
**Pull request by speller26**

### CODE REVIEW

**Comment by dabacon** [comment]
I think this is a duplicate of a previous one 
```
* 5 points for each mention of quantum computers solving a major world issue, without a reference to how this might arise. "We'll solve global warming by using our magic quantum computer.
```
Let's make it 10pts, delete the 5 pt one, and use your wording (which I like better) :)

**Review by dabacon — CHANGES_REQUESTED** [review]
see comment above

**Comment by speller26** [comment]
D'oh, don't know how I missed that one

**Review by dabacon — APPROVED** [review]
Perfect!  Thanks.

**Pull request merged**
